name: spring CICD

on:
  push:
    branches: [ 'develop' ]

env:
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: |
          docker build -t spring-app .
          
      - name: Docker build & push to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/eday-spring .
          docker push ${{ secrets.DOCKER_USERNAME }}/eday-spring

        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: www.eday.site
        username: ubuntu
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          if [ "$(docker ps -q -f name=spring-container)" ]; then
            docker stop spring-container
            docker rm spring-container
          fi
          docker pull ${{ secrets.DOCKER_USERNAME }}/eday-spring
          docker run -d --name spring-container -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/eday-spring
          docker image prune -f
